// Code generated by "stringer -type=Format"; DO NOT EDIT.

package wrp

import "fmt"

const _Format_name = "MsgpackJSONlastFormat"

var _Format_index = [...]uint8{0, 7, 11, 21}

func (i Format) String() string {
	if i < 0 || i >= Format(len(_Format_index)-1) {
		return fmt.Sprintf("Format(%d)", i)
	}
	return _Format_name[_Format_index[i]:_Format_index[i+1]]
}
