// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package wrp

import "fmt"

const _MessageType_name = "AuthorizationStatusMessageTypeSimpleRequestResponseMessageTypeSimpleEventMessageTypeCreateMessageTypeRetrieveMessageTypeUpdateMessageTypeDeleteMessageTypeServiceRegistrationMessageTypeServiceAliveMessageTypelastMessageType"

var _MessageType_index = [...]uint8{0, 30, 62, 84, 101, 120, 137, 154, 184, 207, 222}

func (i MessageType) String() string {
	i -= 2
	if i < 0 || i >= MessageType(len(_MessageType_index)-1) {
		return fmt.Sprintf("MessageType(%d)", i+2)
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
