// Code generated by "stringer -type=ErrorType"; DO NOT EDIT.

package xerrors

import "strconv"

const _ErrorType_name = "UnknownErrorURLErrorNetErrorRequestCanceledErrorRequestCanceledConErrorTemporaryErrorTimeoutErrorContextDeadlineExceededErrorContextCanceledError"

var _ErrorType_index = [...]uint8{0, 12, 20, 28, 48, 71, 85, 97, 125, 145}

func (i ErrorType) String() string {
	if i < 0 || i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
