# SPDX-FileCopyrightText: 2025 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
