# SPDX-FileCopyrightText: 2025 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
linters-settings:
  misspell:
    locale: US
  errorlint:
    # Report non-wrapping error creation using fmt.Errorf
    errorf: false

linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gosec
    - misspell
    - prealloc
    - unconvert
  disable:
    - errcheck
    - ineffassign
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    # rules:
    #   - linters:
    #       - dupl
    paths:
      - _test.go
      - concurrent/*
      - health/*
      - server/*

      - service/*
      - webhook/aws/*
      - xviper/*
      - xmetrics/*
