version: "2"
linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gosec
    - misspell
    - prealloc
    - unconvert
  disable:
    - errcheck
    - ineffassign
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    # rules:
    #   - linters:
    #       - dupl
    paths:
      - _test.go
      - concurrent/*
      - health/*
      - server/*

      - service/*
      - webhook/aws/*
      - xviper/*
      - xmetrics/*
