version = 1
SPDX-PackageName = "webpa-common"
SPDX-PackageSupplier = "John Bass <john_bass2@cable.comcast.com>"
SPDX-PackageDownloadLocation = "https://github.com/xmidt-org/webpa-common"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2025 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"
