# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: "Dependabot auto approval"

# yamllint disable-line
on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  approve:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/approve-dependabot.yml@2b9dd377731fc812fba09296b6c3bf5f9e6664ff # v4.13.1
    secrets: inherit
