# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: "Dependabot auto approval"

# yamllint disable-line
on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  approve:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/approve-dependabot.yml@ec035dbc93dc306b76ff03e8df07bfef772104b1 # v4.13.0
    secrets: inherit
