# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: "Auto Release"

# yamllint disable-line
on:
  schedule: # Run every day at 12:00 UTC
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/auto-releaser.yml@7f729aa96350db9c0120bc3eb07f4fc062a77508 # v4.13.2
    secrets: inherit
