# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: CI

# yamllint disable-line
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - MAINTAINERS.md
      - LICENSE
      - NOTICE
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: write
  packages: write

jobs:
  ci:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/ci.yml@ec035dbc93dc306b76ff03e8df07bfef772104b1 # v4.13.0
    with:
      release-type: library
      yaml-lint-skip: false
    secrets: inherit
