# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - MAINTAINERS.md
      - LICENSE
      - NOTICE
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: read
  contents: write
  packages: write

jobs:
  ci:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/ci.yml@aff0471aa7e2f96ddb059beb178f63747a7cc57e # v4.9.41
    with:
      style-skip:     true
      yaml-lint-skip: true
      lint-skip:      true
      release-type:   library
    secrets: inherit
