# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: "PROJ: xmidt-team"

# yamllint disable-line
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  proj:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/proj.yml@6ffc106b98d2050b7f7b2cf6903cac31e6f1591d # v4.13.3
    secrets: inherit
