# SPDX-FileCopyrightText: 2025 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'PROJ: xmidt-team'

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  package:
    uses: xmidt-org/.github/.github/workflows/proj-template.yml@proj-v1
    secrets: inherit
