# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: "PROJ: xmidt-team"

# yamllint disable-line
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  proj:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/proj.yml@643f1637b0ca329da0289e421b40860c02029e53 # v4.12.21
    secrets: inherit
